services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: redi
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: