"""all primary keys made non nullable

Revision ID: 12f14de019c8
Revises: 
Create Date: 2025-08-16 12:51:15.784992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f14de019c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_channels', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True,
               schema='public_mart')
    op.alter_column('dim_dates', 'id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True,
               schema='public_mart')
    op.alter_column('fact_messages', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               schema='public_mart')
    op.alter_column('fct_image_detections', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True,
               schema='public_mart')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fct_image_detections', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               schema='public_mart')
    op.alter_column('fact_messages', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True,
               schema='public_mart')
    op.alter_column('dim_dates', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True,
               schema='public_mart')
    op.alter_column('dim_channels', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True,
               schema='public_mart')
    # ### end Alembic commands ###
